[input]

transform_path = 'out/registration'

additional_data = [
    'examples/data/geojson_example/001 M- V7 HES.vsi - 20x_BF_03.ome.tif',
    'examples/data/geojson_example/001 M- V7 HES.vsi - 20x_BF_03.geojson',
    ]

[[input.transform_data]]

path = 'examples/data/geojson_example/001 M- V7 HES.vsi - 20x_BF_03.ome.tif'
type = 'image'

[[input.transform_data]]

path = 'examples/data/geojson_example/001 M- V7 HES.vsi - 20x_BF_03.ome.tif'
type = 'annotation'
invert_axis = true

[[input.transform_data]]

path = 'examples/data/geojson_example/001 M- V7 HES.vsi - 20x_BF_03.geojson'
type = 'geojson'

[[input.transform_data]]

path = 'examples/data/geojson_example/001 M- V7 HES.vsi - 20x_BF_03.csv'
type = 'pointset'
index_col = 0
x_axis = 'x'
y_axis = 'y'

[options]

output_directory = 'out'
path_to_greedy = ''

