#[input_options]
#
# moving_image = MOVING_FILE_PATH
# fixed_image = FIXED_FILE_PATH
# moving_mask = MOVING_MASK_PATH
# fixed_mask = FIXED_MASK_PATH
# path_to_greedy = PATH_TO_GREEDY
# output_directory = PATH_TO_OUTPUT_DIRECTORY
# annotation_path = moving_annotation_path
[options]

temporary_directory = 'tmp2'
store_commandline_logs = false
remove_temporary_directory = false
output_directory = 'out2'


[gfh_options]

resolution = '2048x2048'
temporary_directory = 'tmp2'
do_affine_registration = false
enable_affine_denoising = true
do_nonrigid_registration = true
enable_nonrigid_denoising = false
moving_sr = 50
moving_sp = 45
fixed_sr = 96
fixed_sp = 13
pre_downsampling_factor = 12
store_commandline_logs = true
remove_temporary_directory = true
keep_affine_transform_unbounded = true

[gfh_options.greedy]

s1 = 20.0
s2 = 20.0
kernel_size = 10
number_rigid_iterations = 10000
ia = 'ia-com-init'
affine_iteration_pyramid = [100, 100, 100, 50, 10]
deformable_pyramid_iterations = [100, 100, 100, 50, 10]
n_threads = 1
use_sv = false
use_svlb = false
yolo_segmentation_min_size = 5000