FROM ubuntu:22.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
RUN apt-get update && apt-get -y install cmake protobuf-compiler
RUN apt-get update && apt-get upgrade -y && apt-get -y --no-install-recommends install \
    build-essential \
    clang \
    gdb \
    wget \
    freeglut3-dev
RUN apt-get -y install libinsighttoolkit5-dev
RUN wget https://www.vtk.org/files/release/9.3/VTK-9.3.0.tar.gz 
RUN tar xfvz VTK-9.3.0.tar.gz 
RUN cd VTK-9.3.0/ && mkdir build && cd build && cmake .. && make -j 8 && make install

RUN git clone https://github.com/pyushkevich/greedy.git
RUN cd greedy && mkdir build && cd build && cmake .. && make -j 8
ENV PATH="$PATH:/greedy/build"

ENTRYPOINT ["greedy"]
