FROM mwess89/greedy:1.3.0-alpha

SHELL ["/bin/bash", "-c"]
RUN apt update && apt-get install -y software-properties-common curl
RUN apt update --fix-missing
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN echo $PATH
RUN echo $HOME
ENV PATH=/root/.local/bin:$PATH
RUN source /root/.local/bin/env
RUN mkdir /app
WORKDIR /app
RUN uv venv --python 3.11
ENV PATH=/app/.venv/bin/:$PATH
RUN source .venv/bin/activate

RUN apt install libvips-dev -y
# Install openjdk and maven for bioformats
RUN apt install openjdk-21-jdk -y
RUN mkdir /temp
WORKDIR /temp
RUN wget -qO- https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz | tar xfvz -
ENV PATH="$PATH:/temp/apache-maven-3.9.11/bin" 
WORKDIR /app

# Install GreedyFHist
RUN uv pip install git+https://github.com/mwess/greedyfhist@v0.0.3-rc6
RUN which greedyfhist
RUN mkdir /data

ENTRYPOINT ["greedyfhist"]