FROM mwess89/greedy:1.3.0-alpha

RUN apt update && apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt install -y python3.10
# RUN apt install -y python3.10 python3.10-venv python3.10-dev
RUN apt install python3-pip -y
RUN apt install libvips-dev -y
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
RUN pip --version
RUN pip install git+https://github.com/mwess/greedyfhist@v0.0.3

ENTRYPOINT ["greedyfhist"]

