[options]

output_directory = 'group_out'
path_to_greedy = ''


[gfh_options]

pre_sampling_factor = 'auto'
pre_sampling_auto_factor = 3500
do_affine_registration = true
do_nonrigid_registration = true
temporary_directory = 'tmp'
remove_temporary_directory = true

[gfh_options.affine_registration_options]

dim = 2
resolution = [1024, 1024]
kernel_size = 10
cost_function = 'ncc'
rigid_iterations = 10000
ia = 'ia-com-init'
iteration_pyramid = [100, 50, 10]
n_threads = 8
keep_affine_transform_unbounded = true
dof = 6

[gfh_options.affine_registration_options.preprocessing_options]
moving_sr = 30
moving_sp = 25
fixed_sr = 30
fixed_sp = 25
temporary_directory = 'tmp'
remove_temporary_directory = true
yolo_segmentation_min_size = 5000
enable_denoising = true


[gfh_options.nonrigid_registration_options]
dim = 2
resolution = [1024, 1024]
s1 = 5.0
s2 = 5.0
kernel_size = 10
cost_function = 'ncc'
ia = 'ia-com-init'
iteration_pyramid = [100, 100, 50, 10]
n_threads = 8
use_sv = false
use_svlb = false

[gfh_options.nonrigid_registration_options.preprocessing_options]
moving_sr = 30
moving_sp = 25
fixed_sr = 30
fixed_sp = 25
temporary_directory = 'tmp'
remove_temporary_directory = true
yolo_segmentation_min_size = 5000
enable_denoising = false


[input]
[input.section1]
[input.section1.reference_image]

path = '../groupwise_examples/hes.tif'
type = 'tif'

[[input.section1.additional_data]]

path = '../groupwise_examples/hes_ps.csv'
type = 'pointset'
index_col = 0

[[input.section1.additional_data]]

path = '../groupwise_examples/hes_mask.tif'
is_annotation = true

[input.section2]
[input.section2.reference_image]

path = '../groupwise_examples/mts.tif'

[input.section2.reference_mask]

path = '../groupwise_examples/mts_mask.tif'

[[input.section2.additional_data]]

path = '../groupwise_examples/mts_ps.csv'


[input.section3]
[input.section3.reference_image]

path = '../groupwise_examples/ihc.tif'